# Generated by Django 3.1.13 on 2023-06-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20230606_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=70, unique=True, verbose_name='usuario')),
                ('clave', models.CharField(max_length=8, verbose_name='clave')),
                ('mail', models.CharField(max_length=20, verbose_name='mail')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='dni')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['usuario'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='Imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog/media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Titulo',
            field=models.CharField(default='Titulo', max_length=50, unique=True, verbose_name='Titulo'),
        ),
    ]
