# Generated by Django 3.1.13 on 2023-06-08 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20230608_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_usuario',
            name='confirmar_clave',
            field=models.CharField(default=datetime.datetime(2023, 6, 8, 18, 23, 29, 527429, tzinfo=utc), max_length=8, verbose_name='confirmar_clave'),
            preserve_default=False,
        ),
    ]
