# Generated by Django 3.1.13 on 2023-06-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20230608_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog'),
        ),
    ]
