# Generated by Django 4.2.2 on 2023-06-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('Blog', '0008_alter_post_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.DeleteModel(
            name='Registro_usuario',
        ),
    ]
