# Generated by Django 4.2.2 on 2023-06-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
