# Generated by Django 4.2.2 on 2023-06-20 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_post_usuario_delete_registro_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuario_avatar',
        ),
    ]
